const screens=[...document.querySelectorAll('.screen')];const nav=[...document.querySelectorAll('nav button')];function showScreen(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.target===id));window.scrollTo({top:0,behavior:'smooth'})}nav.forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.target)));function openComposer(){document.getElementById('composer').classList.add('open')}function closeComposer(){document.getElementById('composer').classList.remove('open')}document.getElementById('composer').addEventListener('click',e=>{if(e.target.id==='composer')closeComposer()});

if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}

const ua=navigator.userAgent;const isIOS=/iPhone|iPad|iPod/i.test(ua);const isAndroid=/Android/i.test(ua);const isStandalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;const deviceName=isIOS?'iPhone/iPad':isAndroid?'Android':'Phone';const hour=new Date().getHours();const greeting=hour<5?'Still up, Brother?':hour<12?'Good morning, Brother.':hour<17?'Good afternoon, Brother.':hour<21?'Good evening, Brother.':'Night check-in, Brother.';const title=document.querySelector('#today h1');if(title)title.textContent=greeting;

let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;showInstallCard()});function installMarkup(){const iosText='Tap Share, then “Add to Home Screen.”';const defaultText='Install Men of God on this device.';return `<div id="installCard" class="installCard"><h3>Put Men of God on your phone.</h3><p>${isIOS?iosText:defaultText}</p><button id="installNow">${isIOS?'Show iPhone steps':'Install app'}</button><button class="later" id="installLater">Not now</button><div class="deviceLine">Detected: ${deviceName} · Local time ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</div></div>`}function showInstallCard(){if(isStandalone||document.getElementById('installCard')||localStorage.getItem('mogInstallDismissed')==='1')return;document.body.insertAdjacentHTML('beforeend',installMarkup());document.getElementById('installLater').onclick=()=>{localStorage.setItem('mogInstallDismissed','1');document.getElementById('installCard')?.remove()};document.getElementById('installNow').onclick=async()=>{if(isIOS){alert('On iPhone: tap the Share button in Safari, then tap “Add to Home Screen,” then Add.');return}if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installCard')?.remove()}}}

window.addEventListener('load',()=>setTimeout(showInstallCard,900));window.addEventListener('appinstalled',()=>{document.getElementById('installCard')?.remove();localStorage.setItem('mogInstalled','1')});

const installMeta=document.createElement('meta');installMeta.name='apple-mobile-web-app-capable';installMeta.content='yes';document.head.appendChild(installMeta);const statusMeta=document.createElement('meta');statusMeta.name='apple-mobile-web-app-status-bar-style';statusMeta.content='black-translucent';document.head.appendChild(statusMeta);const titleMeta=document.createElement('meta');titleMeta.name='apple-mobile-web-app-title';titleMeta.content='Men of God';document.head.appendChild(titleMeta);const appleIcon=document.createElement('link');appleIcon.rel='apple-touch-icon';appleIcon.href='./icon.svg';document.head.appendChild(appleIcon);

const localContext={device:deviceName,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,locale:navigator.language,installed:isStandalone};localStorage.setItem('mogDeviceContext',JSON.stringify(localContext));